name: Merge on Green

on:
  workflow_run:
    types: [completed]

jobs:
  call-merge-on-green:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.name != 'Merge on Green'

    uses: artsy/duchamp/.github/workflows/merge-on-green.yml@main

    with:
      sha: ${{ github.event.workflow_run.head_sha }}

    permissions:
      contents: write
      pull-requests: write
      issues: read

    secrets: inherit
